services:
  - type: web
    name: retrod-chatbot
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py ingest_knowledge
    startCommand: gunicorn retrod_backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: retrod-db
          property: connectionString
      - key: PMS_BACKEND_URL
        value: "https://pms-backend-wp9b.onrender.com"
      - key: PMS_USERNAME
        value: "aarav"
      - key: PMS_PASSWORD
        value: "123456"
      - key: GROQ_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_FROM
        value: "whatsapp:+14155238886"
      - key: TWILIO_CONTENT_SID
        value: "HXffa2708ffafdb33293c7aa54fb8d02db"

databases:
  - name: retrod-db
    databaseName: retrod_db
    user: retrod_user
