# Generated by Django 5.2.16 on 2026-07-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("staff_assistance", "Staff Assistance"),
                            ("website_navigation", "Website Navigation"),
                            ("pms_workflow", "PMS Workflow"),
                            ("general_faq", "General FAQ"),
                        ],
                        default="pms_workflow",
                        max_length=50,
                    ),
                ),
                (
                    "source_doc",
                    models.CharField(default="SRS-PMS_Retrod", max_length=255),
                ),
                (
                    "embedding_json",
                    models.JSONField(
                        blank=True, help_text="Stored vector embedding list", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
